### ISSUE TITLE
Images and annotations(2D) in mo2cap2 dataset seem to be misaligned 

### ISSUE THREAD

**Issue by vhehduatks** [jmpark0808/Ego-STAN#49]
![image](https://github.com/user-attachments/assets/0f321c88-9d33-4c97-8d28-0aabef007ca5)

array([[170.48444607, 195.85060182],
       [209.76063996, 182.06944849],
       [209.18125289, 159.30975026],
       [200.66867527, 144.00597239],
       [143.11292486, 192.39134802],
       [148.84316542, 178.55270456],
       [149.81205227, 164.62105121],
       [182.24785177, 151.14496095],
       [182.10578036, 151.19194651],
       [184.42285936, 158.93867127],
       [182.18854678, 152.88507762],
       [165.28019211, 154.5198145 ],
       [164.61862113, 146.23721418],
       [165.92826082, 143.61015986],
       [161.52020929, 136.29468376]])

![mo2cap2_chunk_0001_000000](https://github.com/user-attachments/assets/8e43fbf4-6547-418e-9a49-9383dd90f26e)

The array above is a 2D joint extracted from mo2cap2_chunk_0001_000000.png and json, and visualizing it gives the following joint coordinates
Just in case,  also extract MO2CAP2 DATA directly from inside the HDF5 file and visualize it, but the result is the same. And it's not just one image, almost all images in the trainset are like this...
I would like to check if anyone else has encountered the same situation and how to solve it. 
![image](https://github.com/user-attachments/assets/84f96fe0-1318-4e5f-87de-5d904565762e)

![image](https://github.com/user-attachments/assets/094d1def-80fb-4c7c-9f49-392c7728f491)
![image](https://github.com/user-attachments/assets/cea256fd-26c5-4b5b-a19d-05591e5b9e3d)

and shared my visualization code
``` python
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import json


# Load the image
image_path = r'F:\extracted_mo2cap2_dataset\TrainSet\mo2cap2_chunk_0001\rgba\mo2cap2_chunk_0001_000007.png'
img = Image.open(image_path)
# Coordinates to plot
json_path = r'F:\extracted_mo2cap2_dataset\TrainSet\mo2cap2_chunk_0001\json\mo2cap2_chunk_0001_000007.json'
with open(json_path) as f:
	json_data = json.load(f)

coordinates = json_data
# Plot the image
plt.figure(figsize=(5, 5))
plt.imshow(img)

x = np.array([coordinates[key]["2d"][0] for key in coordinates])
y = np.array([coordinates[key]["2d"][1] for key in coordinates])

plt.scatter(x, y)

# Display the plot

plt.show()
```

---

I solved the misalignment in a very simple way, but I realize this is not a fundamental solution.
![image](https://github.com/user-attachments/assets/9a09e752-49a7-45fb-b07b-5ae0aeab351a)

**Comment by jmpark0808** [comment]
Hi @vhehduatks , thank you for the first issue!

You are on the right track. As you can see from our code, we also have the -33.
https://github.com/jmpark0808/Ego-STAN/blob/77622fc0df608dac334214fb77448564539295fb/dataset/mo2cap2.py#L202

Check our code from dataset/mo2cap2.py

**Comment by vhehduatks** [comment]
Thank you for your response.
Would it be possible to know the config information you used when training the mo2cap2 baseline (epoch)?
I would like to try to reimplement mo2cap2, but I am having a hard time because the training details are not provided.

![image](https://github.com/user-attachments/assets/12e5c9f4-dd97-43d6-bd1a-775fd723c23a)
![image](https://github.com/user-attachments/assets/9d41a477-0b75-414d-90bb-a296eb89642d)
(mo2cap2 paper)

**Comment by jmpark0808** [comment]
@vhehduatks Ah yes we also had trouble trying to reproduce what mo2cap2 had. We tried to follow the description from the paper as closely as possible but we didn't come close to what they produced.
